### ISSUE TITLE
Add Valley-Shaped functions

### ISSUE THREAD

**Issue by kvoss** [kvoss/optobench#5]
Add missing functions from Valley-Shaped category from [SFU](https://www.sfu.ca/~ssurjano/optimization.html)

**Comment by dillonago** [comment]
Hi, I would like to help with this. Would that be fine?

**Comment by kvoss** [comment]
@dillonago absolutely! :+1:

**Comment by dillonago** [comment]
I cannot make a branch, is it possible for me to make a new branch so I can start? Thanks!

**Comment by kvoss** [comment]
Are you able to make a branch locally and then submit a pull request?

**Comment by dillonago** [comment]
I was able to make a branch locally, but when I try to push the branch to github it gives me error 403. I don't think I have permissions to push to this repo.

**Comment by kvoss** [comment]
I'm looking into it right now! :) Good find @dillonago !

**Comment by dillonago** [comment]
Ok perfect! I will start working on the functions and add them when I am complete. Thanks for letting me help out!

**Comment by kvoss** [comment]
I invited you to collaborate. Havent found a clear answer on how to allow people who are not collaborators to push branches. Looking more into that.

**Comment by kvoss** [comment]
It seems that a workflow for github is to:
1. fork a repo
2. checkout your forked version of the repo
3. make local changes
4. push to your forked repo
5. create pull request from the forked repo

I found a [guide](https://kbroman.org/github_tutorial/pages/fork.html) listing these steps.

Hope that helps for the future! :sweat_smile:

**Comment by dillonago** [comment]
@kvoss please check it out and let me know if it works as intended. Thanks!
